{"time":"2025-06-03T16:17:20.6762509+08:00","level":"INFO","msg":"stream: starting","core version":"0.19.11","symlink path":"E:\\Learning_Documents\\Computer_Vision_and_Intelligent_Medical_Image_Analysis\\BIG_HOMEWORK\\LVIT-main\\wandb\\run-20250603_161720-73obvn1y\\logs\\debug-core.log"}
{"time":"2025-06-03T16:17:43.0914184+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-06-03T16:18:06.3051967+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-06-03T16:18:31.9440533+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-06-03T16:19:01.0434398+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
