{"time":"2025-06-03T16:13:20.0151476+08:00","level":"INFO","msg":"stream: starting","core version":"0.19.11","symlink path":"E:\\Learning_Documents\\Computer_Vision_and_Intelligent_Medical_Image_Analysis\\BIG_HOMEWORK\\LVIT-main\\wandb\\run-20250603_161319-p0uk0q7t\\logs\\debug-core.log"}
{"time":"2025-06-03T16:13:41.9973416+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-06-03T16:14:05.1583019+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-06-03T16:14:31.1590842+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-06-03T16:15:01.0613032+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
