{"time":"2025-06-03T16:15:59.9744661+08:00","level":"INFO","msg":"stream: starting","core version":"0.19.11","symlink path":"E:\\Learning_Documents\\Computer_Vision_and_Intelligent_Medical_Image_Analysis\\BIG_HOMEWORK\\LVIT-main\\wandb\\run-20250603_161559-cuwrzi57\\logs\\debug-core.log"}
{"time":"2025-06-03T16:16:22.0860625+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-06-03T16:16:45.438047+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
