{"time":"2025-06-03T16:11:47.4543586+08:00","level":"INFO","msg":"stream: starting","core version":"0.19.11","symlink path":"E:\\Learning_Documents\\Computer_Vision_and_Intelligent_Medical_Image_Analysis\\BIG_HOMEWORK\\LVIT-main\\wandb\\run-20250603_161147-up1qccsn\\logs\\debug-core.log"}
{"time":"2025-06-03T16:12:10.1394178+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-06-03T16:12:33.367135+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
{"time":"2025-06-03T16:12:59.0494566+08:00","level":"INFO","msg":"api: retrying error","error":"Post \"https://api.wandb.ai/graphql\": dial tcp 35.186.228.49:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."}
